version: '3'

services:
  acmanagerdb:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  acmanager-server:
    image: kun368/acmanager:master
    ports:
      - 8105:8080
    depends_on:
      - acmanagerdb
    links:
      - acmanagerdb